import type { RouteManifest } from '@/core/file-router/route-manifest'

/**
 * Generates the component map TypeScript code.
 * Returns the file content as a string.
 */
export function buildComponentMap(manifest: RouteManifest) {
  // Collect all unique component paths from manifest
  const componentPaths = new Set<string>()
  
  for (const route of Object.values(manifest)) {
    if (route.screen)
      componentPaths.add(route.screen)

    for (const layout of route.layouts ?? [])
      componentPaths.add(layout)
  }
  
  // Sort for consistent output
  const sortedPaths = Array.from(componentPaths).sort()
  
  // Generate imports and exports
  const imports: string[] = []
  const exports: string[] = []
  
  for (let i = 0; i < sortedPaths.length; i++) {
    const componentPath = sortedPaths[i]
    const varName = `Component${i}`
    
    // Convert: /app/home/screen.tsx → ../src/app/home/screen
    const importPath = componentPath.replace('/app/', './app/') + '.js'

    imports.push(`import ${varName} from '${importPath}'`)
    exports.push(`  '${componentPath}': ${varName},`)
  }
  
  // Generate file content
  return [
    '// Auto-generated by @idlesummer/pen',
    '// Do not edit this file manually',
    '',
    ...imports,
    '',
    'export const components = {',
    ...exports,
    '}\n',
  ].join('\n')
}
