import { writeFileSync } from 'fs'
import { join } from 'path'
import { dedent } from '@/lib/dedent'
import type { RouteManifest } from '@/core/build/manifest'

/**
 * Generates the component map TypeScript file.
 * Creates imports and exports for all screens and layouts.
 */
export function generateComponentMap(manifest: RouteManifest, outputDir: string): void {
  // Collect all unique component paths from manifest
  const componentPaths = new Set<string>()
  
  for (const route of Object.values(manifest)) {
    if (route.screen)
      componentPaths.add(route.screen)

    if (route.layouts)
      for (const layout of route.layouts)
        componentPaths.add(layout)
  }
  
  // Sort for consistent output
  const sortedPaths = Array.from(componentPaths).sort()
  
  // Generate imports and exports
  const imports: string[] = []
  const exports: string[] = []
  
  for (let i = 0; i < sortedPaths.length; i++) {
    const componentPath = sortedPaths[i]
    const varName = `Component${i}`
    
    // Convert: /app/home/screen.tsx → ../src/app/home/screen
    const importPath = componentPath
      .replace('/app/', '../src/app/')
      .replace('.tsx', '')

    imports.push(`import ${varName} from '${importPath}'`)
    exports.push(`  '${componentPath}': ${varName},`)
  }
  
  // Generate file content
  const content = dedent(`
    // Auto-generated by @idlesummer/pen
    // Do not edit this file manually

    import type { ComponentType } from 'react'
    ${imports.join('\n')}

    export const components: Record<string, ComponentType> = {
    ${exports.join('\n')}
    }
  `)
  
  // Write to file
  const componentsPath = join(outputDir, 'components.ts')
  writeFileSync(componentsPath, content, 'utf-8')
  
  console.log(`   ✓ Generated ${componentsPath}`)
}
