import { DefaultFallback } from './renderer/components/DefaultBoundary'
import { ErrorFallback } from './renderer/components/ErrorBoundary'
import { validateAsyncPages, validateComponentExports } from './renderer/setup/validate'

export { App } from './renderer/App'
export { renderMatch } from './renderer/render'
export type { ComponentMap, RouteComponent, RouteModule } from './renderer/types/component-map'
export { createDefaultExportMap } from './renderer/setup/module-mapper'
export { createAppProps } from './renderer/setup/app-props'
export type { Params } from './renderer/types/params'
export { isAsyncComponent } from './renderer/components/PageComponent'
export type { PageComponent } from './renderer/components/PageComponent'
export type { LayoutComponent } from './renderer/components/LayoutComponent'
export { ErrorBoundary } from './renderer/components/ErrorBoundary'
export type { ErrorComponentProps, ErrorComponent } from './renderer/components/ErrorBoundary'
export { DefaultBoundary, notFound, DefaultSignal } from './renderer/components/DefaultBoundary'
export type { DefaultComponent } from './renderer/components/DefaultBoundary'
export { LoadingBoundary } from './renderer/components/LoadingBoundary'
export type { LoadingComponent } from './renderer/components/LoadingBoundary'
export { NavigationProvider } from './navigation/NavigationProvider'
export { useHistory } from './navigation/hooks/use-history'
export { useNavigate } from './navigation/hooks/use-navigate'
export { usePathname } from './navigation/hooks/use-pathname'
export { useRouter } from './navigation/hooks/use-router'
export { useSearchParams } from './navigation/hooks/use-search-params'

export const Fallback = { Default: DefaultFallback, Error: ErrorFallback }
export const validate = { componentExports: validateComponentExports, asyncPages: validateAsyncPages }
