import { removeExtension } from '@/lib/path-utils'
import type { ComponentRegistry } from './component-registry'

/**
 * Generates the component map TypeScript code.
 * Returns the file content as a string.
 */
export function buildComponentMap(registry: ComponentRegistry) {
  const sortedEntries = Object.entries(registry).sort(([a], [b]) => a.localeCompare(b))

  // Generate imports and exports
  const imports: string[] = []
  const exports: string[] = []

  for (const [i, [componentId, sourcePath]] of sortedEntries.entries()) {
    const varName = `Component${i}`

    // Convert: /app/home/screen.tsx → ./app/home/screen.js
    const importPath = removeExtension(sourcePath).replace('/app/', './app/') + '.js'
    imports.push(`import ${varName} from '${importPath}'`)
    exports.push(`  '${componentId}': ${varName},`)
  }

  // Generate file content
  return [
    '// Auto-generated by @idlesummer/pen',
    '// Do not edit this file manually',
    '',
    ...imports,
    '',
    'export const components = {',
    ...exports,
    '}\n',
  ].join('\n')
}
